version: 2
workflows:
  version: 2
  test:
    jobs:
    - build-3.7
    - build-3.6
    - build-2.7

jobs:
  build-3.7: &test-template
    docker:
      - image: circleci/python:3.7-jessie
    steps:
      - checkout
      - restore_cache:
          key: deps2-{{ .Environment.CIRCLE_JOB}}-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Create virtualenv
          command: |
            if [ "${CIRCLE_JOB}" == "build-2.7" ]; then
                virtualenv env
            else
                python3 -m venv env
            fi
            . env/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps2-{{ .Environment.CIRCLE_JOB}}-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "env"
      - run:
          name: Running tests
          command: |
            . env/bin/activate
            python manage.py test
      - run:
          name: Linting code
          command: |
            . env/bin/activate
            flake8
      - store_artifacts:
          path: test-reports/
          destination: python_app
  build-3.6:
    <<: *test-template
    docker:
      - image: circleci/python:3.6-jessie
   build-3.5:
     <<: *test-template
     docker:
       - image: circleci/python:3.5-jessie
  build-2.7:
    <<: *test-template
    docker:
      - image: circleci/python:2.7-jessie
