version: 2
workflows:
  version: 2
  test:
    jobs:
    #- build-3.6
    - build-3.7
    #- build-3.8

jobs:
  build-3.7: &test-template
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - restore_cache:
          key: deps2-{{ .Environment.CIRCLE_JOB}}-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Create virtualenv
          command: |
            virtualenv env --python=python3
            . env/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps2-{{ .Environment.CIRCLE_JOB}}-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "env"
      - run:
          name: Running tests
          command: |
            . env/bin/activate
            python manage.py test
      - run:
          name: Linting code
          command: |
            . env/bin/activate
            flake8
      - store_artifacts:
          path: test-reports/
          destination: python_app
  build-3.6:
    <<: *test-template
    docker:
      - image: circleci/python:3.6
  build-3.8:
    <<: *test-template
    docker:
      - image: circleci/python:3.8
